#include "asul.h"
#include "Def.h"
#include "Sources/BaseScrollPage.h"
#include "Sources/COM_HomeWidget/T_Home.h"
#include "Sources/COM_SettingWidget/T_SettingScreen.h"
#include "Sources/COM_AboutWidget/T_About.h"

#include "Sources/GlobalSettings.h"
#include "Sources/GlobalFunc.h"
#include <ElaApplication.h>




Asul::Asul(QWidget *parent) : ElaWindow(parent) {

  this->setIsDefaultClosed(false);
  connect(this, &ElaWindow::closeButtonClicked, [=]() {
    bool askClose =
        GlobalFunc::askDialog(this, tr("关闭"), tr("确定要关闭此程序?"));
    if (askClose) {
      Asul::closeWindow();
      qApp->quit();
    }
  });
  this->setWindowTitle(gSets->getProgramName() +
                       QString(" [%1]").arg(gSets->getProgramVersion()));
  this->setFixedSize(QSize(1200, 800));
  this->AsulWindowINIT(
      this, AsulINIT(true,                                   // CardVisible
                     ":///Sources/icon/splash_${THEME}.png", // CardPixmap
                     gSets->getProgramName(),                // CardTitle
                     "@" + gSets->getProgramAuthor(),        // CardSubTitle
                     ElaAppBarType::CloseButtonHint |
                         ElaAppBarType::MaximizeButtonHint |
                         ElaAppBarType::MinimizeButtonHint // ButtonFlag
                     ));



  InstallPage(tr("主页"), T_Home, ElaIconType::House);
  AddExpanderNode(tr("样例组"), Sample, ElaIconType::DiceD12);
  for(int i=1;i<=50;i++){
    INSTALL_SAMPLE_PAGE(i);
  }
  
  InstallAboutFooter(tr("关于"), T_About, _about);
  InstallFooter(tr("设置"), T_SettingScreen, _setting, ElaIconType::Gear);
  
  connect(T_HomePage /*Auto-Generated By Macro*/, &T_Home::showSettingPage,
          [=]() { this->navigation(_setting); });
}

Asul::~Asul() {}
