#include "asul.h"
#include "Sources/COM_HomeWidget/T_Home.h"
#include "Sources/COM_SettingWidget/T_SettingScreen.h"
#include "Sources/COM_AboutWidget/T_About.h"

#include "Sources/GlobalSettings.h"
#include "Sources/GlobalFunc.h"
#include <ElaApplication.h>

Asul::Asul(QWidget *parent)
    : ElaWindow(parent){

    this->setIsDefaultClosed(false);
    connect(this,&ElaWindow::closeButtonClicked,[=](){
        bool askClose=GlobalFunc::askDialog(this,tr("关闭"),tr("确定要关闭此程序?"));
        if(askClose){
            Asul::closeWindow();
        }
    });
    this->setWindowTitle("AsulSwiftDevelopKit");
    this->AsulWindowINIT(this,AsulINIT(true, //CardVisible
                                  ":///Sources/icon/splash_${THEME}.png", //CardPixmap
                                  "Asul", //CardTitle
                                  "AsulKit", //CardSubTitle
                                  ElaAppBarType::CloseButtonHint|ElaAppBarType::MaximizeButtonHint|ElaAppBarType::MinimizeButtonHint //ButtonFlag
                        ));

    InstallPage(tr("主页"),T_Home,ElaIconType::House);

    InstallAboutFooter(T_About,_about);
    InstallFooter(tr("设置"),T_SettingScreen,_setting,ElaIconType::Gear);

    connect(T_HomePage/*Auto-Generated By Macro*/,&T_Home::showSettingPage,[=](){
        this->navigation(_setting);
    });
}

Asul::~Asul() {}
