name: Qt CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.3.0
      with:
        version: '6.7.*'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        use-official: true
        aqtversion: '==3.1.19'
        email: ${{ secrets.QTEMAIL }}
        pw: ${{ secrets.QTPASSWD }}
        # modules: qtbase qtwidgets qtnetwork  # 显式指定需要安装的Qt模块

    - name: Set up MinGW
      uses: coffeebe4code/setup-mingw@v1-beta-2
      with:
        platform: x64
        version: 11.2.0

    - name: Verify MinGW installation
      run: |
        mingw32-make --version
        g++ --version
      shell: bash

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..

    - name: Build
      run: |
        cd build
        cmake --build . --config Release -- -j$(nproc)

    - name: Create binary package
      run: |
        mkdir dist
        cp build/ASUL.exe dist/  # 替换为实际的可执行文件名称
        windeployqt dist/ASUL.exe  # 收集Qt依赖项

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/
        retention-days: 7
